### ISSUE TITLE
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/pusher-js/dist/web/pusher.js?v=121ebf41' does not provide an export named 'default'

### ISSUE THREAD

**Issue by Jonston** [manchenkoff/nuxt-laravel-echo#59] opened 2024-11-24 16:50 UTC
Hello. It's me again. This time I'm having problems with another of your packages. After installation and configuration I receive this message
ncaught SyntaxError: The requested module '/_nuxt/node_modules/pusher-js/dist/web/pusher.js?v=121ebf41' does not provide an export named 'default'

**Comment by manchenkoff** [comment] 2024-11-24 17:57
Hey @Jonston, have you done this step from the readme file?

```typescript
export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      include: ['pusher-js'],
    },
  },
})
```

**Comment by Jonston** [comment] 2024-11-24 19:12
Thank you. The plugin always listens to the web socket server. Is it possible to temporarily disable it so that there are no errors in the console?

**Comment by manchenkoff** [comment] 2024-11-24 22:54
> Is it possible to temporarily disable it so that there are no errors in the console?

No, right now you can either disable the module or ignore the errors since they do not affect the behaviour of your app. However, it is a nice idea and technically it is possible to do in the future, but I will have some time to implement that in a couple of weeks. Feel free to create a Feature Request issue. 

I'm closing this one since the original problem is solved.

**Closed by manchenkoff** 2024-11-24 22:54 UTC
Labels: bug

**Comment by EvanSchleret** [comment] 2025-01-06 15:17
Hi @manchenkoff,

I have the same problem and yes, I added the portion of code that is in the readme file regarding vite.

It looks like the problem I encountered on another lib: https://github.com/BayBreezy/nuxt-tour/issues/148#issuecomment-2558526400.

Could it be a problem with users who use pnpm?

![image](https://github.com/user-attachments/assets/eba8455e-4326-4246-86f5-823388e1f4b3)

Thanks for your help.

**Comment by manchenkoff** [comment] 2025-01-06 16:12
Hey @EvanSchleret, yes, I think they are the same issues. To be honest, I never tried it with anything but `pnpm` for this package. If the code sample provided in the readme doesn't help, you can raise a new issue and provide more details about your environment there (e.g. vite version, nuxt, etc) and whether it occurs in dev-mode or prod as well. I will try to take a look at it.

**Comment by EvanSchleret** [comment] 2025-01-06 16:16
Ok, no problem. I'll create an issue with a reproduction repo later with all the information that could be useful.

**Comment by EvanSchleret** [comment] 2025-03-04 16:45
@Nks Thanks, Artem already gave me the answer :) But thanks ! https://github.com/manchenkoff/nuxt-laravel-echo/issues/87#issuecomment-2581300925

**Comment by leeovery** [comment] 2025-03-31 17:31
Im seeing this error and no matter what I do I cant get rid of it.

The frustrating thing is that it was all working fine with the optimizeDeps hack. But suddenly it stopped working - I dont recall what i changed either :(

Any ideas? Im about ready to throw my laptop out of the window haha

```
Uncaught SyntaxError: The requested module '/_nuxt/@fs/[redacted]/nuxt-layers/base/node_modules/pusher-js/dist/web/pusher.js?v=08e92e0a' does not provide an export named 'default' (at plugin.client.js?v=08e92e0a:3:8)
```
